# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'db_table': 'project',
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='StatusProject',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'db_table': 'statusProject',
                'verbose_name': 'Project Status',
                'verbose_name_plural': 'Projects Status',
            },
        ),
        migrations.CreateModel(
            name='TypeProject',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'db_table': 'typeProject',
                'verbose_name': 'Project Type',
                'verbose_name_plural': 'Projects Type',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='statusProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='projects.StatusProject'),
        ),
        migrations.AddField(
            model_name='project',
            name='typeProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='projects.TypeProject'),
        ),
    ]
